# Generated by Django 5.2.3 on 2026-04-22 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barber',
            options={'ordering': ['-rating'], 'verbose_name': 'Барбер', 'verbose_name_plural': 'Барберы'},
        ),
        migrations.AlterField(
            model_name='barber',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='barbers/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='bio',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='display_name',
            field=models.CharField(max_length=100, verbose_name='Отображаемое имя'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступен для записи'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='specialty',
            field=models.CharField(default='Master Barber', max_length=100, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barber_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
