# Generated by Django 5.2.3 on 2026-05-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0002_alter_barber_options_alter_barber_avatar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barber',
            options={'ordering': ['-is_default', '-rating'], 'verbose_name': 'Барбер', 'verbose_name_plural': 'Барберы'},
        ),
        migrations.AddField(
            model_name='barber',
            name='experience_years',
            field=models.PositiveIntegerField(default=1, verbose_name='Стаж (лет)'),
        ),
        migrations.AddField(
            model_name='barber',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='По умолчанию в своей категории'),
        ),
        migrations.AddField(
            model_name='barber',
            name='level',
            field=models.CharField(choices=[('Рейнджер', 'Рейнджер'), ('Шкипер', 'Шкипер'), ('Капитан', 'Капитан')], default='Рейнджер', max_length=20, verbose_name='Уровень квалификации'),
        ),
    ]
