# Generated by Django 5.2.3 on 2026-05-07 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0003_alter_barber_options_barber_experience_years_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barber',
            options={'verbose_name': 'Барбер', 'verbose_name_plural': 'Барберы'},
        ),
        migrations.RemoveField(
            model_name='barber',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='barber',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='barber',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='barber',
            name='specialty',
        ),
        migrations.AlterField(
            model_name='barber',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='barbers/', verbose_name='Фото (круглое в шторке)'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='display_name',
            field=models.CharField(max_length=100, verbose_name='Имя барбера'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='experience_years',
            field=models.PositiveIntegerField(default=1, verbose_name='Стаж в Van Blade (лет)'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='level',
            field=models.CharField(choices=[('SKIPPER', 'Шкиперы'), ('RANGER', 'Рейнджеры'), ('CAPTAIN', 'Капитаны')], default='RANGER', max_length=20, verbose_name='Квалификация'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barber_profile', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт пользователя (необязательно)'),
        ),
    ]
