# Generated by Django 5.2.3 on 2026-05-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0004_alter_barber_options_remove_barber_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='barbers/', verbose_name='Фото'),
        ),
    ]
