# Generated by Django 5.2.3 on 2026-05-07 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0005_alter_barber_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barber',
            name='experience_years',
        ),
        migrations.AddField(
            model_name='barber',
            name='experience_months',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Стаж работы (в месяцах)'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='level',
            field=models.CharField(choices=[('SKIPPER', 'Шкипер'), ('RANGER', 'Рейнджер'), ('CAPTAIN', 'Капитан')], default='RANGER', max_length=20, verbose_name='Квалификация'),
        ),
    ]
