# Generated by Django 5.2.3 on 2026-05-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0006_remove_barber_experience_years_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='level',
            field=models.CharField(choices=[('Рейнджер', 'Рейнджер'), ('Шкипер', 'Шкипер'), ('Капитан', 'Капитан')], default='RANGER', max_length=20, verbose_name='Квалификация'),
        ),
    ]
