# Generated by Django 5.2.3 on 2026-05-07 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0008_alter_barber_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Занято')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='barbers.barber', verbose_name='Барбер')),
            ],
            options={
                'verbose_name': 'Слот времени',
                'verbose_name_plural': 'Слоты времени',
                'ordering': ['date', 'time'],
                'unique_together': {('barber', 'date', 'time')},
            },
        ),
    ]
