# Generated by Django 5.2.3 on 2026-05-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0009_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='level',
            field=models.CharField(choices=[('Матрос', 'Матрос'), ('Шкипер', 'Шкипер'), ('Капитан', 'Капитан')], default='Матрос', max_length=20, verbose_name='Квалификация'),
        ),
    ]
