# Generated by Django 5.2.3 on 2026-05-05 06:30

import django.core.validators
import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название работы / Клиент')),
                ('image', models.ImageField(upload_to='gallery/', validators=[gallery.models.validate_image_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Фотография')),
                ('image_type', models.CharField(choices=[('square', 'Квадрат (1:1) — Стандарт'), ('wide', 'Широкий (16:9) — Горизонтальный'), ('tall', 'Высокий (9:16) — Вертикальный')], default='square', help_text='Определяет, как фото впишется в сетку на сайте', max_length=10, verbose_name='Тип формата')),
                ('show_on_home', models.BooleanField(default=False, help_text='Если выбрано, фото попадет в слайдер на главной (макс. 10)', verbose_name='Показывать на главной')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Работа мастера',
                'verbose_name_plural': 'Наши работы',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
