# Generated by Django 5.2.3 on 2026-05-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='image_type',
            field=models.CharField(choices=[('square', 'Квадрат (1:1) — Стандарт'), ('wide', 'Широкий (16:9) — Горизонтальный'), ('tall', 'Высокий (9:16) — Вертикальный'), ('big', 'Акцент (2x2) — Большой квадрат')], default='square', help_text='Определяет, как фото впишется в сетку на сайте', max_length=10, verbose_name='Тип формата'),
        ),
    ]
