# Generated by Django 5.2.3 on 2026-05-05 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_work_image_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='title',
        ),
    ]
