# Generated by Django 5.2.3 on 2026-05-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_work_image_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='image_type',
            field=models.CharField(choices=[('square', 'Квадрат (1:1) — Стандарт'), ('tall', 'Портрет (3:4) — Вертикальный'), ('wide', 'Широкий (16:9) — Горизонтальный'), ('big', 'Акцент (2x2) — Большой')], default='square', help_text='Определяет, как фото впишется в сетку на сайте', max_length=10, verbose_name='Тип формата'),
        ),
    ]
