# Generated by Django 5.2.3 on 2026-05-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_work_image_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='image_type',
            field=models.CharField(choices=[('square', 'Базовый квадрат (1x1)'), ('big', 'Большой квадрат (2x2)'), ('horizontal', 'Горизонтальный (2x1)'), ('vertical', 'Вертикальный (1x2)'), ('long', 'Длинный вертикальный (1x3)')], default='square', help_text='Определяет, как фото впишется в сетку на сайте', max_length=15, verbose_name='Тип формата'),
        ),
        migrations.AlterField(
            model_name='work',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='work',
            name='show_on_home',
            field=models.BooleanField(default=False, verbose_name='Показывать на главной'),
        ),
    ]
