# Generated by Django 5.2.3 on 2026-05-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_work_image_type_alter_work_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='image_type',
            field=models.CharField(choices=[('square', 'Базовый квадрат (1x1)'), ('big', 'Большой квадрат (2x2)'), ('horizontal', 'Горизонтальный (2x1)'), ('portrait', 'Портрет 4:5'), ('vertical', 'Высокий вертикальный (1x2)'), ('long', 'Длинный (1x3)')], default='square', help_text='Определяет, как фото впишется в сетку на сайте', max_length=15, verbose_name='Тип формата'),
        ),
    ]
