# Generated by Django 5.2.3 on 2026-04-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='barber_level',
            field=models.CharField(choices=[('ranger', 'Рейнджер'), ('skipper', 'Шкипер'), ('captain', 'Капитан')], default='ranger', max_length=20),
        ),
    ]
