# Generated by Django 5.2.3 on 2026-04-20 17:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0001_initial'),
        ('services', '0002_service_barber_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['barber_level', 'name'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='duration_minutes',
        ),
        migrations.AddField(
            model_name='service',
            name='barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='barbers.barber', verbose_name='Исполнитель (Барбер)'),
        ),
        migrations.AddField(
            model_name='service',
            name='duration_range',
            field=models.CharField(choices=[('15', '10–30 минут'), ('30', '30–60 минут'), ('60', '60+ минут')], default='30', max_length=10, verbose_name='Длительность (интервал)'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Фото услуги'),
        ),
        migrations.AddField(
            model_name='service',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Креативный подзаголовок (1-2 предложения)', max_length=120, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='service',
            name='barber_level',
            field=models.CharField(choices=[('ranger', 'Рейнджер'), ('skipper', 'Шкипер'), ('captain', 'Капитан')], default='ranger', max_length=20, verbose_name='Уровень квалификации'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='Описание услуги (до 600 символов)', max_length=600, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна?'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена (₽)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL-идентификатор'),
        ),
    ]
