# Generated by Django 5.2.3 on 2026-04-21 16:15

import django.core.validators
import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='duration_range',
        ),
        migrations.AddField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30, help_text='От 15 до 120 минут', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(120)], verbose_name='Длительность (минуты)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', validators=[services.models.validate_image_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Фото услуги'),
        ),
    ]
