# Generated by Django 5.2.3 on 2026-04-22 11:23

import django.core.validators
import django.db.models.deletion
import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0002_alter_barber_options_alter_barber_avatar_and_more'),
        ('services', '0004_remove_service_duration_range_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория услуг', 'verbose_name_plural': 'Категории услуг'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='duration_minutes',
        ),
        migrations.AddField(
            model_name='service',
            name='duration_range',
            field=models.CharField(choices=[('15', '10–30 минут'), ('30', '30–60 минут'), ('60', '60+ минут')], default='30', max_length=10, verbose_name='Длительность процедуры'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Идентификатор иконки', max_length=50, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL-идентификатор (slug)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='barbers.barber', verbose_name='Барбер (исполнитель)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='barber_level',
            field=models.CharField(choices=[('ranger', 'Рейнджер'), ('skipper', 'Шкипер'), ('captain', 'Капитан')], default='ranger', max_length=20, verbose_name='Уровень квалификации барбера'),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', validators=[services.models.validate_image_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Фотография услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна (отображать на сайте)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL-идентификатор (slug)'),
        ),
    ]
