# Generated by Django 5.2.3 on 2026-04-22 11:40

import django.core.validators
import django.db.models.deletion
import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0002_alter_barber_options_alter_barber_avatar_and_more'),
        ('services', '0005_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='duration_range',
        ),
        migrations.AddField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30, help_text='От 15 до 120 минут', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(120)], verbose_name='Длительность (минуты)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL-идентификатор'),
        ),
        migrations.AlterField(
            model_name='service',
            name='barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='barbers.barber', verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='service',
            name='barber_level',
            field=models.CharField(choices=[('ranger', 'Рейнджер'), ('skipper', 'Шкипер'), ('captain', 'Капитан')], default='ranger', max_length=20, verbose_name='Уровень квалификации'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='Описание услуги', max_length=600, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', validators=[services.models.validate_image_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Фото услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL-идентификатор'),
        ),
        migrations.AlterField(
            model_name='service',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Креативный подзаголовок', max_length=120, verbose_name='Подзаголовок'),
        ),
    ]
