# Generated by Django 5.2.3 on 2026-04-25 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_servicevariant_and_migrate_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
    ]
