# Generated by Django 5.2.3 on 2026-04-25 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_service_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicevariant',
            name='duration_minutes',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='servicevariant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
