# Generated by Django 5.2.3 on 2026-04-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_servicevariant_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicevariant',
            name='barber_level',
            field=models.CharField(choices=[('Рейнджер', 'Рейнджер'), ('Шкипер', 'Шкипер'), ('Капитан', 'Капитан')], max_length=20),
        ),
    ]
