# Generated by Django 5.2.3 on 2026-04-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_servicevariant_barber_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicevariant',
            name='description',
            field=models.TextField(blank=True, help_text='Особенности работы барбера этой квалификации', max_length=500, verbose_name='Описание уровня'),
        ),
    ]
