# Generated by Django 5.2.3 on 2026-04-26 11:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_servicevariant_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicevariant',
            options={'ordering': ['price'], 'verbose_name': 'Вариант услуги', 'verbose_name_plural': 'Варианты услуг'},
        ),
        migrations.AlterField(
            model_name='servicevariant',
            name='barber_level',
            field=models.CharField(choices=[('Рейнджер', 'Рейнджер'), ('Шкипер', 'Шкипер'), ('Капитан', 'Капитан')], max_length=20, verbose_name='Квалификация барбера'),
        ),
        migrations.AlterField(
            model_name='servicevariant',
            name='description',
            field=models.TextField(blank=True, help_text='Расскажите, чем отличается услуга у этого мастера', max_length=550, verbose_name='Описание для этого уровня'),
        ),
        migrations.AlterField(
            model_name='servicevariant',
            name='duration_minutes',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(120)], verbose_name='Длительность (мин.)'),
        ),
        migrations.AlterField(
            model_name='servicevariant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='servicevariant',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='services.service', verbose_name='Основная услуга'),
        ),
    ]
