# Generated by Django 5.2.3 on 2026-05-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_alter_servicevariant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicevariant',
            name='barber_level',
            field=models.CharField(choices=[('Матрос', 'Матрос'), ('Шкипер', 'Шкипер'), ('Капитан', 'Капитан')], max_length=20, verbose_name='Квалификация барбера'),
        ),
    ]
